# TCL File Generated by Component Editor 24.1
# Thu Jun 11 14:53:29 CEST 2026
# DO NOT MODIFY


# 
# RMIIPhy "RMIIPhy" v1.0.0
# ModMAC Development 2026.06.11.14:53:29
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module RMIIPhy
# 
set_module_property DESCRIPTION ""
set_module_property NAME RMIIPhy
set_module_property VERSION 1.0.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ModMAC/MII
set_module_property AUTHOR "ModMAC Development"
set_module_property DISPLAY_NAME RMIIPhy
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RMIIPhyAvalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file RMIIPhyAvalon.vhd VHDL PATH RMIIPhyAvalon.vhd TOP_LEVEL_FILE
add_fileset_file RMIIPhy.vhd VHDL PATH RMIIPhy.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock avalon_clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock avalon_clk
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avalon_read read Input 1
add_interface_port avalon_slave avalon_read_data readdata Output 32
add_interface_port avalon_slave avalon_address address Input 2
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_clk
# 
add_interface avalon_clk clock end
set_interface_property avalon_clk clockRate 0
set_interface_property avalon_clk ENABLED true
set_interface_property avalon_clk EXPORT_OF ""
set_interface_property avalon_clk PORT_NAME_MAP ""
set_interface_property avalon_clk CMSIS_SVD_VARIABLES ""
set_interface_property avalon_clk SVD_ADDRESS_GROUP ""

add_interface_port avalon_clk avalon_clk clk Input 1


# 
# connection point rmii
# 
add_interface rmii conduit end
set_interface_property rmii associatedClock avalon_clk
set_interface_property rmii associatedReset ""
set_interface_property rmii ENABLED true
set_interface_property rmii EXPORT_OF ""
set_interface_property rmii PORT_NAME_MAP ""
set_interface_property rmii CMSIS_SVD_VARIABLES ""
set_interface_property rmii SVD_ADDRESS_GROUP ""

add_interface_port rmii rmii_rxd rmii_rxd Input 2
add_interface_port rmii rmii_ref_clk rmii_ref_clk Input 1
add_interface_port rmii rmii_crs_dv rmii_crs_dv Input 1


# 
# connection point xii_out
# 
add_interface xii_out conduit end
set_interface_property xii_out associatedClock avalon_clk
set_interface_property xii_out associatedReset ""
set_interface_property xii_out ENABLED true
set_interface_property xii_out EXPORT_OF ""
set_interface_property xii_out PORT_NAME_MAP ""
set_interface_property xii_out CMSIS_SVD_VARIABLES ""
set_interface_property xii_out SVD_ADDRESS_GROUP ""

add_interface_port xii_out xii_o_c xii_c Output 1
add_interface_port xii_out xii_o_d xii_d Output 8
add_interface_port xii_out xii_o_e xii_e Output 1
add_interface_port xii_out xii_o_r xii_r Input 1

