# TCL File Generated by Component Editor 24.1
# Thu Nov 27 21:14:23 CET 2025
# DO NOT MODIFY


# 
# MDIOClause22 "MDIOClause22" v1.0
#  2025.11.27.21:14:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module MDIOClause22
# 
set_module_property DESCRIPTION ""
set_module_property NAME MDIOClause22
set_module_property VERSION 1.0.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ModMAC/MDIO
set_module_property AUTHOR "ModMAC Development"
set_module_property DISPLAY_NAME MDIOClause22
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MDIOClause22Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file MDIOClause22Avalon.vhd VHDL PATH MDIOClause22Avalon.vhd TOP_LEVEL_FILE
add_fileset_file MDIOClause22.vhd VHDL PATH MDIOClause22.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock avalon_clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point mdio_clk
# 
add_interface mdio_clk clock end
set_interface_property mdio_clk clockRate 0
set_interface_property mdio_clk ENABLED true
set_interface_property mdio_clk EXPORT_OF ""
set_interface_property mdio_clk PORT_NAME_MAP ""
set_interface_property mdio_clk CMSIS_SVD_VARIABLES ""
set_interface_property mdio_clk SVD_ADDRESS_GROUP ""

add_interface_port mdio_clk mdio_clk clk Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock avalon_clk
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avalon_read read Input 1
add_interface_port avalon_slave avalon_read_data readdata Output 32
add_interface_port avalon_slave avalon_write write Input 1
add_interface_port avalon_slave avalon_write_data writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_clk
# 
add_interface avalon_clk clock end
set_interface_property avalon_clk clockRate 0
set_interface_property avalon_clk ENABLED true
set_interface_property avalon_clk EXPORT_OF ""
set_interface_property avalon_clk PORT_NAME_MAP ""
set_interface_property avalon_clk CMSIS_SVD_VARIABLES ""
set_interface_property avalon_clk SVD_ADDRESS_GROUP ""

add_interface_port avalon_clk avalon_clk clk Input 1


# 
# connection point mdio
# 
add_interface mdio conduit end
set_interface_property mdio associatedClock ""
set_interface_property mdio associatedReset ""
set_interface_property mdio ENABLED true
set_interface_property mdio EXPORT_OF ""
set_interface_property mdio PORT_NAME_MAP ""
set_interface_property mdio CMSIS_SVD_VARIABLES ""
set_interface_property mdio SVD_ADDRESS_GROUP ""

add_interface_port mdio mdc mdc Output 1
add_interface_port mdio mdio_out out Output 1
add_interface_port mdio mdio_in in Input 1
add_interface_port mdio mdio_out_enable out_enable Output 1

